name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          distribution: 'adopt'
      - name: Setup network
        run: |
          docker network create --driver bridge Lab1
          docker pull mongo
          docker run -d --name mongo-dbserver --network Lab1 mongo
      - name: Build with Maven
        run: mvn package
      - name: Build
        run: docker build -t Lab1 .
      - name: Run image
        run: docker run --network Lab1 --name devopscontainer Lab1
      - name: view logs
        run: docker logs devopscontainer
